-- Central Utility Script - Step 90
-- Purpose:
-- Grant required access in DBA_DB to SQL Server and SQL Agent service logins
-- detected on central server.

SET NOCOUNT ON;

DECLARE @CentralEndpoint NVARCHAR(256) = N'DBMGMT.cubecloud.local\SQL01,10010';

DECLARE @ServiceLogins TABLE (
    Principal SYSNAME PRIMARY KEY
);

INSERT INTO @ServiceLogins (Principal)
SELECT DISTINCT CAST(s.service_account AS SYSNAME)
FROM sys.dm_server_services s
WHERE s.service_account IS NOT NULL
  AND s.service_account NOT IN (N'LocalSystem', N'NT AUTHORITY\\LocalService', N'NT AUTHORITY\\NetworkService')
  AND (
        s.servicename LIKE N'SQL Server (%'
     OR s.servicename LIKE N'SQL Server Agent (%'
  );

IF NOT EXISTS (SELECT 1 FROM @ServiceLogins)
BEGIN
    RAISERROR(N'No eligible SQL service accounts found in sys.dm_server_services on central.', 16, 1);
    RETURN;
END;

-- Ensure server login exists on central
USE master;

DECLARE @Principal SYSNAME;
DECLARE @sql NVARCHAR(MAX);

DECLARE curCreateLogin CURSOR LOCAL FAST_FORWARD FOR
    SELECT Principal
    FROM @ServiceLogins;

OPEN curCreateLogin;
FETCH NEXT FROM curCreateLogin INTO @Principal;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM sys.server_principals
        WHERE name = @Principal
    )
    BEGIN
        SET @sql = N'CREATE LOGIN ' + QUOTENAME(@Principal) + N' FROM WINDOWS;';
        EXEC(@sql);
    END;

    FETCH NEXT FROM curCreateLogin INTO @Principal;
END;

CLOSE curCreateLogin;
DEALLOCATE curCreateLogin;

-- Ensure database user exists in DBA_DB
USE DBA_DB;

DECLARE curDbUser CURSOR LOCAL FAST_FORWARD FOR
    SELECT Principal
    FROM @ServiceLogins;

OPEN curDbUser;
FETCH NEXT FROM curDbUser INTO @Principal;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM sys.database_principals
        WHERE name = @Principal
    )
    BEGIN
        SET @sql =
            N'CREATE USER ' + QUOTENAME(@Principal) +
            N' FOR LOGIN ' + QUOTENAME(@Principal) + N';';
        EXEC(@sql);
    END;

    FETCH NEXT FROM curDbUser INTO @Principal;
END;

CLOSE curDbUser;
DEALLOCATE curDbUser;

-- Add role membership idempotently
DECLARE curRoles CURSOR LOCAL FAST_FORWARD FOR
    SELECT Principal
    FROM @ServiceLogins;

OPEN curRoles;
FETCH NEXT FROM curRoles INTO @Principal;

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM sys.database_role_members drm
        JOIN sys.database_principals r ON r.principal_id = drm.role_principal_id
        JOIN sys.database_principals m ON m.principal_id = drm.member_principal_id
        WHERE r.name = N'db_datareader' AND m.name = @Principal
    )
    BEGIN
        SET @sql = N'ALTER ROLE [db_datareader] ADD MEMBER ' + QUOTENAME(@Principal) + N';';
        EXEC(@sql);
    END;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.database_role_members drm
        JOIN sys.database_principals r ON r.principal_id = drm.role_principal_id
        JOIN sys.database_principals m ON m.principal_id = drm.member_principal_id
        WHERE r.name = N'db_datawriter' AND m.name = @Principal
    )
    BEGIN
        SET @sql = N'ALTER ROLE [db_datawriter] ADD MEMBER ' + QUOTENAME(@Principal) + N';';
        EXEC(@sql);
    END;

    FETCH NEXT FROM curRoles INTO @Principal;
END;

CLOSE curRoles;
DEALLOCATE curRoles;

-- Selected service accounts on central
SELECT
    N'Selected service account' AS Info,
    l.Principal
FROM @ServiceLogins l
ORDER BY l.Principal;

-- Verification on central
SELECT
    N'Final membership' AS Info,
    m.name AS Principal,
    r.name AS RoleName
FROM sys.database_role_members drm
JOIN sys.database_principals r ON r.principal_id = drm.role_principal_id
JOIN sys.database_principals m ON m.principal_id = drm.member_principal_id
WHERE m.name IN (SELECT Principal FROM @ServiceLogins)
ORDER BY m.name, r.name;

-- Output target-side SQL script (copy and run on TARGET).
DECLARE @TargetScript NVARCHAR(MAX) = N'';

SET @TargetScript = @TargetScript +
N'-- Generated by central step 90' + CHAR(13) + CHAR(10) +
N'-- Run this script on TARGET server' + CHAR(13) + CHAR(10) +
N'SET NOCOUNT ON;' + CHAR(13) + CHAR(10) +
N'DECLARE @CentralEndpoint NVARCHAR(256) = N''' + REPLACE(@CentralEndpoint, N'''', N'''''') + N''';' + CHAR(13) + CHAR(10) +
N'DECLARE @TargetServerName NVARCHAR(256) = CAST(@@SERVERNAME AS NVARCHAR(256));' + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) +
N'USE master;' + CHAR(13) + CHAR(10);

SELECT @TargetScript = @TargetScript +
N'IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N''' + REPLACE(l.Principal, N'''', N'''''') + N''')' + CHAR(13) + CHAR(10) +
N'    EXEC(N''CREATE LOGIN ' + REPLACE(QUOTENAME(l.Principal), N'''', N'''''') + N' FROM WINDOWS;'');' + CHAR(13) + CHAR(10)
FROM @ServiceLogins l
ORDER BY l.Principal;

SET @TargetScript = @TargetScript + CHAR(13) + CHAR(10) +
N'USE DBA_DB;' + CHAR(13) + CHAR(10) +
N'IF OBJECT_ID(N''Monitoring.Servers'', N''U'') IS NULL' + CHAR(13) + CHAR(10) +
N'BEGIN' + CHAR(13) + CHAR(10) +
N'    RAISERROR(N''Monitoring.Servers is missing on TARGET. Run target setup step 02 first.'', 16, 1);' + CHAR(13) + CHAR(10) +
N'    RETURN;' + CHAR(13) + CHAR(10) +
N'END;' + CHAR(13) + CHAR(10);

SELECT @TargetScript = @TargetScript +
N'IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N''' + REPLACE(l.Principal, N'''', N'''''') + N''')' + CHAR(13) + CHAR(10) +
N'    EXEC(N''CREATE USER ' + REPLACE(QUOTENAME(l.Principal), N'''', N'''''') + N' FOR LOGIN ' + REPLACE(QUOTENAME(l.Principal), N'''', N'''''') + N';'');' + CHAR(13) + CHAR(10) +
N'IF NOT EXISTS (' + CHAR(13) + CHAR(10) +
N'    SELECT 1 FROM sys.database_role_members drm' + CHAR(13) + CHAR(10) +
N'    JOIN sys.database_principals r ON r.principal_id = drm.role_principal_id' + CHAR(13) + CHAR(10) +
N'    JOIN sys.database_principals m ON m.principal_id = drm.member_principal_id' + CHAR(13) + CHAR(10) +
N'    WHERE r.name = N''''db_datareader'''' AND m.name = N''' + REPLACE(l.Principal, N'''', N'''''') + N'''' + CHAR(13) + CHAR(10) +
N')' + CHAR(13) + CHAR(10) +
N'    EXEC(N''ALTER ROLE [db_datareader] ADD MEMBER ' + REPLACE(QUOTENAME(l.Principal), N'''', N'''''') + N';'');' + CHAR(13) + CHAR(10) +
N'IF NOT EXISTS (' + CHAR(13) + CHAR(10) +
N'    SELECT 1 FROM sys.database_role_members drm' + CHAR(13) + CHAR(10) +
N'    JOIN sys.database_principals r ON r.principal_id = drm.role_principal_id' + CHAR(13) + CHAR(10) +
N'    JOIN sys.database_principals m ON m.principal_id = drm.member_principal_id' + CHAR(13) + CHAR(10) +
N'    WHERE r.name = N''''db_datawriter'''' AND m.name = N''' + REPLACE(l.Principal, N'''', N'''''') + N'''' + CHAR(13) + CHAR(10) +
N')' + CHAR(13) + CHAR(10) +
N'    EXEC(N''ALTER ROLE [db_datawriter] ADD MEMBER ' + REPLACE(QUOTENAME(l.Principal), N'''', N'''''') + N';'');' + CHAR(13) + CHAR(10)
FROM @ServiceLogins l
ORDER BY l.Principal;

SET @TargetScript = @TargetScript + CHAR(13) + CHAR(10) +
N'MERGE Monitoring.Servers AS dst' + CHAR(13) + CHAR(10) +
N'USING (SELECT CAST(@@SERVERNAME AS NVARCHAR(256)) AS ServerName, @CentralEndpoint AS CentralServerName, CAST(1 AS BIT) AS IsActive) AS src' + CHAR(13) + CHAR(10) +
N'ON dst.ServerName = src.ServerName' + CHAR(13) + CHAR(10) +
N'WHEN MATCHED THEN UPDATE SET dst.CentralServerName = src.CentralServerName, dst.IsActive = src.IsActive, dst.ModifiedAt = GETDATE()' + CHAR(13) + CHAR(10) +
N'WHEN NOT MATCHED THEN INSERT (ServerName, CentralServerName, IsActive) VALUES (src.ServerName, src.CentralServerName, src.IsActive);' + CHAR(13) + CHAR(10) +
N'' + CHAR(13) + CHAR(10) +
N'MERGE Monitoring.Servers AS dst' + CHAR(13) + CHAR(10) +
N'USING (SELECT @CentralEndpoint AS ServerName, @CentralEndpoint AS CentralServerName, CAST(1 AS BIT) AS IsActive) AS src' + CHAR(13) + CHAR(10) +
N'ON dst.ServerName = src.ServerName' + CHAR(13) + CHAR(10) +
N'WHEN MATCHED THEN UPDATE SET dst.CentralServerName = src.CentralServerName, dst.IsActive = src.IsActive, dst.ModifiedAt = GETDATE()' + CHAR(13) + CHAR(10) +
N'WHEN NOT MATCHED THEN INSERT (ServerName, CentralServerName, IsActive) VALUES (src.ServerName, src.CentralServerName, src.IsActive);' + CHAR(13) + CHAR(10) +
N'' + CHAR(13) + CHAR(10) +
N'SELECT N''Final membership on TARGET'' AS Info, m.name AS Principal, r.name AS RoleName' + CHAR(13) + CHAR(10) +
N'FROM sys.database_role_members drm' + CHAR(13) + CHAR(10) +
N'JOIN sys.database_principals r ON r.principal_id = drm.role_principal_id' + CHAR(13) + CHAR(10) +
N'JOIN sys.database_principals m ON m.principal_id = drm.member_principal_id' + CHAR(13) + CHAR(10) +
N'WHERE m.name IN (' +
    STUFF((
        SELECT N',N''' + REPLACE(l2.Principal, N'''', N'''''') + N''''
        FROM @ServiceLogins l2
        ORDER BY l2.Principal
        FOR XML PATH(''), TYPE
    ).value('.', 'NVARCHAR(MAX)'), 1, 1, N'') +
N')' + CHAR(13) + CHAR(10) +
N'ORDER BY m.name, r.name;' + CHAR(13) + CHAR(10) +
N'' + CHAR(13) + CHAR(10) +
N'SELECT N''Local rows on TARGET'' AS Info, ServerName, CentralServerName, IsActive, ModifiedAt' + CHAR(13) + CHAR(10) +
N'FROM Monitoring.Servers' + CHAR(13) + CHAR(10) +
N'WHERE ServerName IN (@TargetServerName, @CentralEndpoint)' + CHAR(13) + CHAR(10) +
N'ORDER BY ServerName;';

SELECT
    N'Run on TARGET' AS Info,
    @TargetScript AS TargetSql;
